[2m2024-02-11T13:52:58.576471Z[0m [34mDEBUG[0m tokio-runtime-worker [2mbackend::handlers::user[0m[2m:[0m res "7c863950ac93c93692995e4732ce1e1466ad74a775352ffbaaf2a4a4ce9b549d0b414a1f3150452be6c7c72c694a7cb46f76452917298d33e67611f0a42addb8"
[2m2024-02-11T13:52:58.578000Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"INSERT INTO Users( login, â€¦" [3mdb.statement[0m[2m=[0m"\n\nINSERT INTO\n  Users(\n    login,\n    username,\n    password\n  )\nVALUES\n  (\n    $1,\n    $1,\n    $2\n  )\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m0 [3melapsed[0m[2m=[0m387.4Âµs
[2m2024-02-11T13:52:58.578146Z[0m [31mERROR[0m tokio-runtime-worker [2mbackend::rejection_handler[0m[2m:[0m Error: DbError(Database(PgDatabaseError { severity: Error, code: "23505", message: "duplicate key value violates unique constraint \"users_login_key\"", detail: Some("Key (login)=(YeahNotSewerSide) already exists."), hint: None, position: None, where: None, schema: Some("public"), table: Some("users"), column: None, data_type: None, constraint: Some("users_login_key"), file: Some("nbtinsert.c"), line: Some(663), routine: Some("_bt_check_unique") }))
