[2m2024-02-11T13:53:01.527519Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"SELECT * FROM Users â€¦" [3mdb.statement[0m[2m=[0m"\n\nSELECT\n  *\nFROM\n  Users\nWHERE\n  login = $1\n  AND password = $2\nLIMIT\n  1\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m1 [3melapsed[0m[2m=[0m322.55Âµs
[2m2024-02-11T13:53:02.651794Z[0m [31mERROR[0m tokio-runtime-worker [2mbackend::rejection_handler[0m[2m:[0m Not Found: Rejection(NotFound)
[2m2024-02-11T13:53:15.286218Z[0m [33m WARN[0m                 main [2mbackend[0m[2m:[0m CTRL+C received, stopping process...
[2m2024-02-11T13:53:27.876498Z[0m [32m INFO[0m main [2mbackend[0m[2m:[0m Starting rest api
[2m2024-02-11T13:53:27.876544Z[0m [34mDEBUG[0m main [2mbackend[0m[2m:[0m Connecting to DB with settings DatabaseSettings { username: "mgwdb", password: "mgwdb", host: "127.0.0.1", port: 5433, database_name: "mgwdb" }
[2m2024-02-11T13:53:27.876557Z[0m [32m INFO[0m main [2mbackend::db[0m[2m:[0m Connecting to database: postgres://mgwdb:mgwdb@127.0.0.1:5433/mgwdb
[2m2024-02-11T13:53:27.876838Z[0m [32m INFO[0m main [2mbackend[0m[2m:[0m The rest api is starting on the 0.0.0.0:8282
[2m2024-02-11T13:53:27.876918Z[0m [32m INFO[0m main [2mbackend[0m[2m:[0m Server started, waiting for CTRL+C
[2m2024-02-11T13:53:27.877095Z[0m [32m INFO[0m main [1mServer::run[0m[1m{[0m[3maddr[0m[2m=[0m0.0.0.0:8282[1m}[0m[2m:[0m [2mwarp::server[0m[2m:[0m listening on http://0.0.0.0:8282
[2m2024-02-11T13:53:31.760974Z[0m [34mDEBUG[0m tokio-runtime-worker [2mbackend::handlers::user[0m[2m:[0m res "7c863950ac93c93692995e4732ce1e1466ad74a775352ffbaaf2a4a4ce9b549d0b414a1f3150452be6c7c72c694a7cb46f76452917298d33e67611f0a42addb8"
[2m2024-02-11T13:53:31.804741Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"INSERT INTO Users( login, â€¦" [3mdb.statement[0m[2m=[0m"\n\nINSERT INTO\n  Users(\n    login,\n    username,\n    password\n  )\nVALUES\n  (\n    $1,\n    $1,\n    $2\n  )\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m0 [3melapsed[0m[2m=[0m1.783511ms
[2m2024-02-11T13:53:31.804857Z[0m [31mERROR[0m tokio-runtime-worker [2mbackend::rejection_handler[0m[2m:[0m Error: DbError(Database(PgDatabaseError { severity: Error, code: "23505", message: "duplicate key value violates unique constraint \"users_login_key\"", detail: Some("Key (login)=(YeahNotSewerSide) already exists."), hint: None, position: None, where: None, schema: Some("public"), table: Some("users"), column: None, data_type: None, constraint: Some("users_login_key"), file: Some("nbtinsert.c"), line: Some(663), routine: Some("_bt_check_unique") }))
[2m2024-02-11T13:53:31.811037Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"SELECT * FROM Users â€¦" [3mdb.statement[0m[2m=[0m"\n\nSELECT\n  *\nFROM\n  Users\nWHERE\n  login = $1\n  AND password = $2\nLIMIT\n  1\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m1 [3melapsed[0m[2m=[0m2.522911ms
[2m2024-02-11T13:53:31.813290Z[0m [31mERROR[0m tokio-runtime-worker [2mbackend::rejection_handler[0m[2m:[0m Not Found: Rejection(NotFound)
[2m2024-02-11T13:53:46.768453Z[0m [34mDEBUG[0m tokio-runtime-worker [2mbackend::handlers::user[0m[2m:[0m res "7c863950ac93c93692995e4732ce1e1466ad74a775352ffbaaf2a4a4ce9b549d0b414a1f3150452be6c7c72c694a7cb46f76452917298d33e67611f0a42addb8"
[2m2024-02-11T13:53:46.769882Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"INSERT INTO Users( login, â€¦" [3mdb.statement[0m[2m=[0m"\n\nINSERT INTO\n  Users(\n    login,\n    username,\n    password\n  )\nVALUES\n  (\n    $1,\n    $1,\n    $2\n  )\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m0 [3melapsed[0m[2m=[0m239.74Âµs
[2m2024-02-11T13:53:46.769990Z[0m [31mERROR[0m tokio-runtime-worker [2mbackend::rejection_handler[0m[2m:[0m Error: DbError(Database(PgDatabaseError { severity: Error, code: "23505", message: "duplicate key value violates unique constraint \"users_login_key\"", detail: Some("Key (login)=(YeahNotSewerSide) already exists."), hint: None, position: None, where: None, schema: Some("public"), table: Some("users"), column: None, data_type: None, constraint: Some("users_login_key"), file: Some("nbtinsert.c"), line: Some(663), routine: Some("_bt_check_unique") }))
[2m2024-02-11T13:53:46.773621Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"SELECT * FROM Users â€¦" [3mdb.statement[0m[2m=[0m"\n\nSELECT\n  *\nFROM\n  Users\nWHERE\n  login = $1\n  AND password = $2\nLIMIT\n  1\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m1 [3melapsed[0m[2m=[0m238.98Âµs
[2m2024-02-11T13:53:46.776891Z[0m [34mDEBUG[0m tokio-runtime-worker [2msqlx::query[0m[2m:[0m [3msummary[0m[2m=[0m"SELECT * FROM Users â€¦" [3mdb.statement[0m[2m=[0m"\n\nSELECT\n  *\nFROM\n  Users\nWHERE\n  id = $1\n" [3mrows_affected[0m[2m=[0m0 [3mrows_returned[0m[2m=[0m1 [3melapsed[0m[2m=[0m480.55Âµs
